[package]
name = "mc_version_parser"
authors = ["smokingplaya"]
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
serde_json = "1.0.125"

[dependencies.serde]
version="1.0.208"
features = ["derive"]